# Generated by Django 2.1.1 on 2018-09-27 09:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import djongo.models.fields
import embed_video.fields
import johukum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('otp_secret', models.CharField(blank=True, max_length=30)),
                ('mobile_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('location', djongo.models.fields.EmbeddedModelField(model_container=johukum.models.LocationInfo, null=True)),
                ('contact', djongo.models.fields.EmbeddedModelField(model_container=johukum.models.ContactPersonInfo, null=True)),
                ('hours_of_operation', djongo.models.fields.EmbeddedModelField(model_container=johukum.models.HoursOfOperation, null=True)),
                ('description', models.TextField(blank=True)),
                ('year_of_establishment', models.IntegerField()),
                ('annual_turnover', models.CharField(choices=[('1-500000', '1-500000'), ('500001-1000000', '500001-1000000'), ('1000001-5000000', '1000001-5000000'), ('5000001-20000000', '5000001-20000000'), ('20000001-50000000', '20000001-50000000'), ('50000001+', '50000001+')], default='1-500000', max_length=30)),
                ('no_of_employees', models.CharField(blank=True, choices=[('1-5', '1-5'), ('6-20', '6-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101-500', '101-500'), ('500+', '500+')], max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('cover_photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('embed_video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Embed Video (Youtube, Vimeo etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(default=None)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'REVIEWED'), (3, 'APPROVED'), (0, 'REJECTED')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('parent', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='johukum.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('location_type', models.IntegerField(choices=[(1, 'Country'), (2, 'City'), (3, 'Area'), (4, 'Thana'), (5, 'Postcode'), (6, 'PostOffice'), (7, 'Division')])),
                ('name', models.CharField(max_length=255)),
                ('prism_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='johukum.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAssociation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'wmv', 'mov', 'mp4'])])),
            ],
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='accepted_payment_methods',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='approved_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='certifications',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.Certification'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='keywords',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.Category'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='photos',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.UploadedImage'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='professional_associations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.ProfessionalAssociation'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='rejected_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='reviewed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='videos',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.UploadedVideo'),
        ),
    ]
