# Generated by Django 2.1.1 on 2018-09-05 08:51

from django.db import migrations

def generate_groups(apps, schema_editor):

    Group = apps.get_model('auth', 'Group')

    default_groups = ['Admin', 'Editor', 'GCO', 'Agent', 'Moderator']

    for g in default_groups:
        Group(name=g).save()   


def generate_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('johukum', 'PaymentMethod')
    default_methods = [
        'Cheques', 'Rocket', 'Visa Card', 'Money Orders', 'M Cash',
        'Master Card', 'Membership Card', 'Credit Card', 'Bkash',
        'Virtual Card', 'Other'
    ]
    for m in default_methods:
        PaymentMethod.objects.create(
            name = m
        )

class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_groups),
        migrations.RunPython(generate_payment_methods),
    ]
