# Generated by Django 2.1.2 on 2018-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_2fa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twofactor_method',
            field=models.IntegerField(choices=[(0, 'Google Authenticator'), (1, 'SMS'), (2, 'Email')], default=0),
        ),
    ]
