# Generated by Django 2.1.2 on 2018-10-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0005_auto_20181008_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
