# Generated by Django 2.1.2 on 2018-10-09 04:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0006_auto_20181008_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
