# Generated by Django 2.1.2 on 2018-10-09 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0008_auto_20181009_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('numbers', djongo.models.fields.ListField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'REVIEWED'), (3, 'APPROVED'), (0, 'REJECTED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(default=None)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='m_approved_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='johukum.Location')),
                ('rejected_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='m_rejected_by', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='m_reviewed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='annual_turnover',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('1-500000', '1-500000'), ('500001-1000000', '500001-1000000'), ('1000001-5000000', '1000001-5000000'), ('5000001-20000000', '5000001-20000000'), ('20000001-50000000', '20000001-50000000'), ('50000001+', '50000001+')], max_length=30, null=True),
        ),
    ]
