# Generated by Django 2.1.2 on 2018-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0010_contactnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactNumber',
        ),
    ]
