# Generated by Django 2.0 on 2019-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0012_auto_20181010_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumberdata',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobilenumberdata',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='Organaization'),
        ),
    ]
