# Generated by Django 2.0 on 2019-01-09 06:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0014_mobilenumberdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumberdata',
            name='land_line_numbers',
            field=djongo.models.fields.ListField(blank=True, default=[], null=True),
        ),
    ]
