# Generated by Django 2.0 on 2019-01-21 08:49

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0016_auto_20190109_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumberdata',
            name='photos',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.UploadedImage'),
        ),
    ]
