# Generated by Django 2.0 on 2019-01-21 09:00

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0017_mobilenumberdata_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumberdata',
            name='keywords',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='johukum.Category'),
        ),
    ]
