# Generated by Django 2.0 on 2019-01-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0018_mobilenumberdata_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilenumberdata',
            old_name='keywords',
            new_name='categories',
        ),
    ]
