# Generated by Django 2.1.7 on 2019-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0022_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='deleted_at',
            field=models.DateField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
