# Generated by Django 2.2.3 on 2019-10-03 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import johukum.models


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0023_auto_20190411_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='approved_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='edit_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='rejected_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='reviewed_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/', validators=[johukum.models.validate_svg]),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='approved_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='edit_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='m_edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='rejected_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumberdata',
            name='reviewed_at',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
