# Generated by Django 2.2.3 on 2019-10-04 05:10

from django.db import migrations, models
import django_extensions.db.fields
import hypereditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0024_auto_20191003_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('content', hypereditor.fields.HyperField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_as_slider',
            field=models.BooleanField(default=False),
        ),
    ]
