# Generated by Django 2.2.3 on 2019-10-04 05:13

from django.db import migrations
import hypereditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0025_auto_20191004_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=hypereditor.fields.HyperField(default=None),
        ),
    ]
