# Generated by Django 2.0 on 2019-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0029_auto_20191120_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
