# Generated by Django 2.0 on 2019-11-20 18:26

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0030_auto_20191120_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='id',
        ),
        migrations.AddField(
            model_name='slider',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
