# Generated by Django 2.0 on 2019-11-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johukum', '0033_auto_20191124_0917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
            ],
        ),
    ]
